import {
    PersonStanding,
    Music,
    Laugh,
    Star,
    Gamepad,
    Video,
    Building,
    NotebookPen,
    Code,
    Paintbrush,
    Pen,
    ChefHat,
    Plane,
    Shirt,
    Vote,
    School,
    Dumbbell,
    Banknote,
    Baby,
    Bitcoin,
    BookOpen,
    Briefcase,
    Camera,
    Car,
    Clapperboard,
    DraftingCompass,
    Gavel,
    Gift,
    GraduationCap,
    Hammer,
    Home,
    Joystick,
    Leaf,
    Megaphone,
    Mic,
    Microscope,
    PartyPopper,
    PawPrint,
    Rocket,
    Sparkles,
    Store,
    Sun,
  } from "lucide-react";
  import { categoryIconsType } from "@/types/UserProps"; // Matches your provided path
  
  export const countryOptions = [
    { value: "AF", label: "Afghanistan", code: "af" },
    { value: "AX", label: "Åland Islands", code: "ax" },
    { value: "AL", label: "Albania", code: "al" },
    { value: "DZ", label: "Algeria", code: "dz" },
    { value: "AS", label: "American Samoa", code: "as" },
    { value: "AD", label: "Andorra", code: "ad" },
    { value: "AO", label: "Angola", code: "ao" },
    { value: "AI", label: "Anguilla", code: "ai" },
    { value: "AQ", label: "Antarctica", code: "aq" },
    { value: "AG", label: "Antigua and Barbuda", code: "ag" },
    { value: "AR", label: "Argentina", code: "ar" },
    { value: "AM", label: "Armenia", code: "am" },
    { value: "AW", label: "Aruba", code: "aw" },
    { value: "AU", label: "Australia", code: "au" },
    { value: "AT", label: "Austria", code: "at" },
    { value: "AZ", label: "Azerbaijan", code: "az" },
    { value: "BS", label: "Bahamas", code: "bs" },
    { value: "BH", label: "Bahrain", code: "bh" },
    { value: "BD", label: "Bangladesh", code: "bd" },
    { value: "BB", label: "Barbados", code: "bb" },
    { value: "BY", label: "Belarus", code: "by" },
    { value: "BE", label: "Belgium", code: "be" },
    { value: "BZ", label: "Belize", code: "bz" },
    { value: "BJ", label: "Benin", code: "bj" },
    { value: "BM", label: "Bermuda", code: "bm" },
    { value: "BT", label: "Bhutan", code: "bt" },
    { value: "BO", label: "Bolivia", code: "bo" },
    { value: "BQ", label: "Bonaire, Sint Eustatius and Saba", code: "bq" },
    { value: "BA", label: "Bosnia and Herzegovina", code: "ba" },
    { value: "BW", label: "Botswana", code: "bw" },
    { value: "BV", label: "Bouvet Island", code: "bv" },
    { value: "BR", label: "Brazil", code: "br" },
    { value: "IO", label: "British Indian Ocean Territory", code: "io" },
    { value: "BN", label: "Brunei Darussalam", code: "bn" },
    { value: "BG", label: "Bulgaria", code: "bg" },
    { value: "BF", label: "Burkina Faso", code: "bf" },
    { value: "BI", label: "Burundi", code: "bi" },
    { value: "CV", label: "Cabo Verde", code: "cv" },
    { value: "KH", label: "Cambodia", code: "kh" },
    { value: "CM", label: "Cameroon", code: "cm" },
    { value: "CA", label: "Canada", code: "ca" },
    { value: "KY", label: "Cayman Islands", code: "ky" },
    { value: "CF", label: "Central African Republic", code: "cf" },
    { value: "TD", label: "Chad", code: "td" },
    { value: "CL", label: "Chile", code: "cl" },
    { value: "CN", label: "China", code: "cn" },
    { value: "CX", label: "Christmas Island", code: "cx" },
    { value: "CC", label: "Cocos (Keeling) Islands", code: "cc" },
    { value: "CO", label: "Colombia", code: "co" },
    { value: "KM", label: "Comoros", code: "km" },
    { value: "CG", label: "Congo", code: "cg" },
    { value: "CD", label: "Congo, Democratic Republic of the", code: "cd" },
    { value: "CK", label: "Cook Islands", code: "ck" },
    { value: "CR", label: "Costa Rica", code: "cr" },
    { value: "CI", label: "Côte d'Ivoire", code: "ci" },
    { value: "HR", label: "Croatia", code: "hr" },
    { value: "CU", label: "Cuba", code: "cu" },
    { value: "CW", label: "Curaçao", code: "cw" },
    { value: "CY", label: "Cyprus", code: "cy" },
    { value: "CZ", label: "Czech Republic", code: "cz" },
    { value: "DK", label: "Denmark", code: "dk" },
    { value: "DJ", label: "Djibouti", code: "dj" },
    { value: "DM", label: "Dominica", code: "dm" },
    { value: "DO", label: "Dominican Republic", code: "do" },
    { value: "EC", label: "Ecuador", code: "ec" },
    { value: "EG", label: "Egypt", code: "eg" },
    { value: "SV", label: "El Salvador", code: "sv" },
    { value: "GQ", label: "Equatorial Guinea", code: "gq" },
    { value: "ER", label: "Eritrea", code: "er" },
    { value: "EE", label: "Estonia", code: "ee" },
    { value: "SZ", label: "Eswatini", code: "sz" },
    { value: "ET", label: "Ethiopia", code: "et" },
    { value: "FK", label: "Falkland Islands (Malvinas)", code: "fk" },
    { value: "FO", label: "Faroe Islands", code: "fo" },
    { value: "FJ", label: "Fiji", code: "fj" },
    { value: "FI", label: "Finland", code: "fi" },
    { value: "FR", label: "France", code: "fr" },
    { value: "GF", label: "French Guiana", code: "gf" },
    { value: "PF", label: "French Polynesia", code: "pf" },
    { value: "TF", label: "French Southern Territories", code: "tf" },
    { value: "GA", label: "Gabon", code: "ga" },
    { value: "GM", label: "Gambia", code: "gm" },
    { value: "GE", label: "Georgia", code: "ge" },
    { value: "DE", label: "Germany", code: "de" },
    { value: "GH", label: "Ghana", code: "gh" },
    { value: "GI", label: "Gibraltar", code: "gi" },
    { value: "GR", label: "Greece", code: "gr" },
    { value: "GL", label: "Greenland", code: "gl" },
    { value: "GD", label: "Grenada", code: "gd" },
    { value: "GP", label: "Guadeloupe", code: "gp" },
    { value: "GU", label: "Guam", code: "gu" },
    { value: "GT", label: "Guatemala", code: "gt" },
    { value: "GG", label: "Guernsey", code: "gg" },
    { value: "GN", label: "Guinea", code: "gn" },
    { value: "GW", label: "Guinea-Bissau", code: "gw" },
    { value: "GY", label: "Guyana", code: "gy" },
    { value: "HT", label: "Haiti", code: "ht" },
    { value: "HM", label: "Heard Island and McDonald Islands", code: "hm" },
    { value: "VA", label: "Holy See", code: "va" },
    { value: "HN", label: "Honduras", code: "hn" },
    { value: "HK", label: "Hong Kong", code: "hk" },
    { value: "HU", label: "Hungary", code: "hu" },
    { value: "IS", label: "Iceland", code: "is" },
    { value: "IN", label: "India", code: "in" },
    { value: "ID", label: "Indonesia", code: "id" },
    { value: "IR", label: "Iran", code: "ir" },
    { value: "IQ", label: "Iraq", code: "iq" },
    { value: "IE", label: "Ireland", code: "ie" },
    { value: "IM", label: "Isle of Man", code: "im" },
    { value: "IL", label: "Israel", code: "il" },
    { value: "IT", label: "Italy", code: "it" },
    { value: "JM", label: "Jamaica", code: "jm" },
    { value: "JP", label: "Japan", code: "jp" },
    { value: "JE", label: "Jersey", code: "je" },
    { value: "JO", label: "Jordan", code: "jo" },
    { value: "KZ", label: "Kazakhstan", code: "kz" },
    { value: "KE", label: "Kenya", code: "ke" },
    { value: "KI", label: "Kiribati", code: "ki" },
    { value: "KP", label: "Korea, Democratic People's Republic of", code: "kp" },
    { value: "KR", label: "Korea, Republic of", code: "kr" },
    { value: "KW", label: "Kuwait", code: "kw" },
    { value: "KG", label: "Kyrgyzstan", code: "kg" },
    { value: "LA", label: "Lao People's Democratic Republic", code: "la" },
    { value: "LV", label: "Latvia", code: "lv" },
    { value: "LB", label: "Lebanon", code: "lb" },
    { value: "LS", label: "Lesotho", code: "ls" },
    { value: "LR", label: "Liberia", code: "lr" },
    { value: "LY", label: "Libya", code: "ly" },
    { value: "LI", label: "Liechtenstein", code: "li" },
    { value: "LT", label: "Lithuania", code: "lt" },
    { value: "LU", label: "Luxembourg", code: "lu" },
    { value: "MO", label: "Macao", code: "mo" },
    { value: "MG", label: "Madagascar", code: "mg" },
    { value: "MW", label: "Malawi", code: "mw" },
    { value: "MY", label: "Malaysia", code: "my" },
    { value: "MV", label: "Maldives", code: "mv" },
    { value: "ML", label: "Mali", code: "ml" },
    { value: "MT", label: "Malta", code: "mt" },
    { value: "MH", label: "Marshall Islands", code: "mh" },
    { value: "MQ", label: "Martinique", code: "mq" },
    { value: "MR", label: "Mauritania", code: "mr" },
    { value: "MU", label: "Mauritius", code: "mu" },
    { value: "YT", label: "Mayotte", code: "yt" },
    { value: "MX", label: "Mexico", code: "mx" },
    { value: "FM", label: "Micronesia", code: "fm" },
    { value: "MD", label: "Moldova", code: "md" },
    { value: "MC", label: "Monaco", code: "mc" },
    { value: "MN", label: "Mongolia", code: "mn" },
    { value: "ME", label: "Montenegro", code: "me" },
    { value: "MS", label: "Montserrat", code: "ms" },
    { value: "MA", label: "Morocco", code: "ma" },
    { value: "MZ", label: "Mozambique", code: "mz" },
    { value: "MM", label: "Myanmar", code: "mm" },
    { value: "NA", label: "Namibia", code: "na" },
    { value: "NR", label: "Nauru", code: "nr" },
    { value: "NP", label: "Nepal", code: "np" },
    { value: "NL", label: "Netherlands", code: "nl" },
    { value: "NC", label: "New Caledonia", code: "nc" },
    { value: "NZ", label: "New Zealand", code: "nz" },
    { value: "NI", label: "Nicaragua", code: "ni" },
    { value: "NE", label: "Niger", code: "ne" },
    { value: "NG", label: "Nigeria", code: "ng" },
    { value: "NU", label: "Niue", code: "nu" },
    { value: "NF", label: "Norfolk Island", code: "nf" },
    { value: "MP", label: "Northern Mariana Islands", code: "mp" },
    { value: "NO", label: "Norway", code: "no" },
    { value: "OM", label: "Oman", code: "om" },
    { value: "PK", label: "Pakistan", code: "pk" },
    { value: "PW", label: "Palau", code: "pw" },
    { value: "PS", label: "Palestine, State of", code: "ps" },
    { value: "PA", label: "Panama", code: "pa" },
    { value: "PG", label: "Papua New Guinea", code: "pg" },
    { value: "PY", label: "Paraguay", code: "py" },
    { value: "PE", label: "Peru", code: "pe" },
    { value: "PH", label: "Philippines", code: "ph" },
    { value: "PN", label: "Pitcairn", code: "pn" },
    { value: "PL", label: "Poland", code: "pl" },
    { value: "PT", label: "Portugal", code: "pt" },
    { value: "PR", label: "Puerto Rico", code: "pr" },
    { value: "QA", label: "Qatar", code: "qa" },
    { value: "RE", label: "Réunion", code: "re" },
    { value: "RO", label: "Romania", code: "ro" },
    { value: "RU", label: "Russian Federation", code: "ru" },
    { value: "RW", label: "Rwanda", code: "rw" },
    { value: "BL", label: "Saint Barthélemy", code: "bl" },
    { value: "SH", label: "Saint Helena", code: "sh" },
    { value: "KN", label: "Saint Kitts and Nevis", code: "kn" },
    { value: "LC", label: "Saint Lucia", code: "lc" },
    { value: "MF", label: "Saint Martin", code: "mf" },
    { value: "PM", label: "Saint Pierre and Miquelon", code: "pm" },
    { value: "VC", label: "Saint Vincent and the Grenadines", code: "vc" },
    { value: "WS", label: "Samoa", code: "ws" },
    { value: "SM", label: "San Marino", code: "sm" },
    { value: "ST", label: "Sao Tome and Principe", code: "st" },
    { value: "SA", label: "Saudi Arabia", code: "sa" },
    { value: "SN", label: "Senegal", code: "sn" },
    { value: "RS", label: "Serbia", code: "rs" },
    { value: "SC", label: "Seychelles", code: "sc" },
    { value: "SL", label: "Sierra Leone", code: "sl" },
    { value: "SG", label: "Singapore", code: "sg" },
    { value: "SX", label: "Sint Maarten", code: "sx" },
    { value: "SK", label: "Slovakia", code: "sk" },
    { value: "SI", label: "Slovenia", code: "si" },
    { value: "SB", label: "Solomon Islands", code: "sb" },
    { value: "SO", label: "Somalia", code: "so" },
    { value: "ZA", label: "South Africa", code: "za" },
    { value: "GS", label: "South Georgia and the South Sandwich Islands", code: "gs" },
    { value: "SS", label: "South Sudan", code: "ss" },
    { value: "ES", label: "Spain", code: "es" },
    { value: "LK", label: "Sri Lanka", code: "lk" },
    { value: "SD", label: "Sudan", code: "sd" },
    { value: "SR", label: "Suriname", code: "sr" },
    { value: "SJ", label: "Svalbard and Jan Mayen", code: "sj" },
    { value: "SE", label: "Sweden", code: "se" },
    { value: "CH", label: "Switzerland", code: "ch" },
    { value: "SY", label: "Syrian Arab Republic", code: "sy" },
    { value: "TW", label: "Taiwan", code: "tw" },
    { value: "TJ", label: "Tajikistan", code: "tj" },
    { value: "TZ", label: "Tanzania", code: "tz" },
    { value: "TH", label: "Thailand", code: "th" },
    { value: "TL", label: "Timor-Leste", code: "tl" },
    { value: "TG", label: "Togo", code: "tg" },
    { value: "TK", label: "Tokelau", code: "tk" },
    { value: "TO", label: "Tonga", code: "to" },
    { value: "TT", label: "Trinidad and Tobago", code: "tt" },
    { value: "TN", label: "Tunisia", code: "tn" },
    { value: "TR", label: "Turkey", code: "tr" },
    { value: "TM", label: "Turkmenistan", code: "tm" },
    { value: "TC", label: "Turks and Caicos Islands", code: "tc" },
    { value: "TV", label: "Tuvalu", code: "tv" },
    { value: "UG", label: "Uganda", code: "ug" },
    { value: "UA", label: "Ukraine", code: "ua" },
    { value: "AE", label: "United Arab Emirates", code: "ae" },
    { value: "GB", label: "United Kingdom", code: "gb" },
    { value: "US", label: "United States", code: "us" },
    { value: "UM", label: "United States Minor Outlying Islands", code: "um" },
    { value: "UY", label: "Uruguay", code: "uy" },
    { value: "UZ", label: "Uzbekistan", code: "uz" },
    { value: "VU", label: "Vanuatu", code: "vu" },
    { value: "VE", label: "Venezuela", code: "ve" },
    { value: "VN", label: "Vietnam", code: "vn" },
    { value: "VG", label: "Virgin Islands, British", code: "vg" },
    { value: "VI", label: "Virgin Islands, U.S.", code: "vi" },
    { value: "WF", label: "Wallis and Futuna", code: "wf" },
    { value: "EH", label: "Western Sahara", code: "eh" },
    { value: "YE", label: "Yemen", code: "ye" },
    { value: "ZM", label: "Zambia", code: "zm" },
    { value: "ZW", label: "Zimbabwe", code: "zw" },
  ];
  
  export const categoryIcons: categoryIconsType = {
    NONE: <PersonStanding size={16} color="#9CA3AF" />,
    MUSIC: <Music size={16} color="#9CA3AF" />,
    COMEDY: <Laugh size={16} color="#9CA3AF" />,
    CELEBRITY: <Star size={16} color="#9CA3AF" />,
    GAMER: <Gamepad size={16} color="#9CA3AF" />,
    FILM: <Video size={16} color="#9CA3AF" />,
    INFLUENCER: <Star size={16} color="#9CA3AF" />,
    FREELANCER: <NotebookPen size={16} color="#9CA3AF" />,
    COMPANY: <Building size={16} color="#9CA3AF" />,
    MEDIA: <Video size={16} color="#9CA3AF" />,
    TECH: <Code size={16} color="#9CA3AF" />,
    SPORTS: <Dumbbell size={16} color="#9CA3AF" />,
    ARTIST: <Paintbrush size={16} color="#9CA3AF" />,
    WRITER: <Pen size={16} color="#9CA3AF" />,
    FOOD: <ChefHat size={16} color="#9CA3AF" />,
    TRAVEL: <Plane size={16} color="#9CA3AF" />,
    FASHION: <Shirt size={16} color="#9CA3AF" />,
    POLITICS: <Vote size={16} color="#9CA3AF" />,
    EDUCATION: <School size={16} color="#9CA3AF" />,
    HEALTH: <Dumbbell size={16} color="#9CA3AF" />,
    INVESTOR: <Banknote size={16} color="#9CA3AF" />,
    SCIENTIST: <Microscope size={16} color="#9CA3AF" />,
    ACTIVIST: <Megaphone size={16} color="#9CA3AF" />,
    PHOTOGRAPHER: <Camera size={16} color="#9CA3AF" />,
    PODCASTER: <Mic size={16} color="#9CA3AF" />,
    CRYPTO: <Bitcoin size={16} color="#9CA3AF" />,
    ENTREPRENEUR: <Briefcase size={16} color="#9CA3AF" />,
    PARENTING: <Baby size={16} color="#9CA3AF" />,
    DIY: <Hammer size={16} color="#9CA3AF" />,
    GAMING_DEV: <Joystick size={16} color="#9CA3AF" />,
    HISTORY: <BookOpen size={16} color="#9CA3AF" />,
    NATURE: <Leaf size={16} color="#9CA3AF" />,
    AUTOMOTIVE: <Car size={16} color="#9CA3AF" />,
    SPIRITUAL: <Sun size={16} color="#9CA3AF" />,
    MARKETING: <Megaphone size={16} color="#9CA3AF" />,
    LEGAL: <Gavel size={16} color="#9CA3AF" />,
    ANIMAL: <PawPrint size={16} color="#9CA3AF" />,
    BEAUTY: <Sparkles size={16} color="#9CA3AF" />,
    REAL_ESTATE: <Home size={16} color="#9CA3AF" />,
    EVENT_PLANNER: <PartyPopper size={16} color="#9CA3AF" />,
    CHARITY: <Gift size={16} color="#9CA3AF" />,
    ARCHITECTURE: <DraftingCompass size={16} color="#9CA3AF" />,
    MEMES: <Laugh size={16} color="#9CA3AF" />,
    SPACE: <Rocket size={16} color="#9CA3AF" />,
    VLOGGER: <Clapperboard size={16} color="#9CA3AF" />,
    STUDENT: <GraduationCap size={16} color="#9CA3AF" />,
    RETAIL: <Store size={16} color="#9CA3AF" />,
    OTHER: <PersonStanding size={16} color="#9CA3AF" />,
  };
  
  export const socialMediaBaseUrls = {
    tiktok: "https://tiktok.com/@",
    youtube: "https://youtube.com/@",
    facebook: "https://facebook.com/",
    x: "https://x.com/",
    instagram: "https://instagram.com/",
    twitch: "https://twitch.tv/",
    bluesky: "https://bsky.app/profile/",
  };